### PR TITLE
fix(toolkit): diff prints stack name not display name

### LINKED ISSUE #448: cli: `cdk diff` showing logical IDs instead of path
### Describe the bug

Up to 2.1007.0, `cdk diff` showed the stack's path like this:

```
Stack AnonData/DmsPrep
There were no differences

Stack AnonData/Dms
There were no differences
```

From 2.1008.0, `cdk diff` shows the stack's logical ID instead:

```
Stack AnonDataDmsPrep32B87930
There were no differences

Stack AnonDataDms83732FF9
There were no differences
```

This is making copy & pasting hard to commands like `cdk deploy`.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.1007.0

### Expected Behavior

`cdk diff` should print the stack's path.

```
Stack AnonData/DmsPrep
There were no differences

Stack AnonData/Dms
There were no differences
```

### Current Behavior

`cdk diff` is printing the stack's logical ID.

```
Stack AnonDataDmsPrep32B87930
There were no differences

Stack AnonDataDms83732FF9
There were no differences
```

### Reproduction Steps

```
cdk diff
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.1008.0

### Framework Version

_No response_

### Node.js Version

22.15.0

### OS

15.4.1

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by kaizencc**
Fixes #448 

Prior to #301 we were using both `stackName` and `displayName` interchangably in different areas of the CLI. #301 chose to standardize to `stackName`. This PR changes that to `displayName`.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license

### CODE REVIEW

File: packages/@aws-cdk/toolkit-lib/lib/api/diff/diff-formatter.ts [hunk 1]
```diff
@@ -154,7 +154,7 @@ export class DiffFormatter {
     this.ioHelper = props.ioHelper;
     this.oldTemplate = props.templateInfo.oldTemplate;
     this.newTemplate = props.templateInfo.newTemplate;
-    this.stackName = props.templateInfo.newTemplate.stackName;
+    this.stackName = props.templateInfo.newTemplate.displayName ?? props.templateInfo.newTemplate.stackName;
```
Comment (kaizencc) [inline packages/@aws-cdk/toolkit-lib/lib/api/diff/diff-formatter.ts:157]: this is kind of iffy, but i think its safe. diff formatter is using stack name to differentiate _nested stacks_, and i don't think nested stacks can have a display name clash.

**Review by rix0rrr — APPROVED** [review]

**Review by mrgrain — APPROVED** [review]
