### PR TITLE
fix(cdk-assets): indicate correct docker command that failed to execute

### LINKED ISSUE #282: (aws-cdk-cli): Improve error message when 'CDK_DOCKER' environment variable is set
### Describe the bug

https://github.com/aws/aws-cdk-cli/blob/a3b976217064bf10ced4739b28cd95f853172e4a/packages/cdk-assets/lib/private/docker.ts#L229

when CDK_DOCKER is set to custom command or to another agent, please improve the error messaging to the right agent.
ref:: https://github.com/aws/aws-cdk-cli/blob/a3b976217064bf10ced4739b28cd95f853172e4a/packages/cdk-assets/lib/private/docker.ts#L310 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

When CDK_DOCKER environment variable is set, error message should be 

'Unable to execute 'value of CDK_DOCKER' in order to build a container asset. Please install 'CDK_DOCKER' and try again'

### Current Behavior

Even though CDK_DOCKER environment variable is set, error message still shows as 

'Unable to execute 'docker' in order to build a container asset. Please install 'docker' and try again'

### Reproduction Steps

Set environment variable 'CDK_DOCKER' to podman, and transfer image assets.

### Possible Solution

  `Unable to execute '${getDockerCmd()}' to build a container asset. Please install '${getDockerCmd()}' and try again.`,

### Additional Information/Context

_No response_

### CDK CLI Version

latest

### Framework Version

_No response_

### Node.js Version

current

### OS

All

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by isker**
Users may override the executable used (instead of `docker`) by setting the CDK_DOCKER environment variable, but the message of the error thrown when such an executable does not exist was not similarly dynamic. Align the contents of the message with the executable invoked.

Fixes #282.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license

### CODE REVIEW

**Review by mrgrain — APPROVED** [review]

File: packages/cdk-assets/lib/private/docker.ts [hunk 1]
```diff
@@ -226,7 +226,7 @@ export class Docker {
     } catch (e: any) {
       if (e.code === 'ENOENT') {
         throw new Error(
-          "Unable to execute 'docker' in order to build a container asset. Please install 'docker' and try again.",
+          `Unable to execute '${getDockerCmd()}' in order to build a container asset. Please install '${getDockerCmd()}' and try again.`,
```
Comment (mrgrain) [inline packages/cdk-assets/lib/private/docker.ts:229]:
```suggestion
          `Failed to find and execute '${getDockerCmd()}' while attempting to build a container asset. Please install '${getDockerCmd()}' and try again. (Or set the 'CDK_DOCKER ' environment variable to choose a different compatible container client.)`,
```
