### PR TITLE
fix(cdk-assets): `--profile` is ignored while publishing assets

### LINKED ISSUE #212: cdk-assets: Does not use credentials from profile
### Describe the bug

When I use cdk-assets to publish my assets and using a profile, cdk-assets cannot upload them correctly. If I define a default profile and not specify a profile, then cdk-assets successfully uploads my assets.

cdk-assets version 3.1.0:
```
cdk-assets publish -p .\cdk.out\CdkassetTestStack.assets.json --profile cdk-asset-test
```

It seems that the profile parameter is ignored, because if I define a valid default profile, but with no permissions to the destination account, then the upload will fail. Using the v2 cdk-assets, it uses the profile parameter correctly.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.155.126 (cdk-assets)

### Expected Behavior

cdk-assets should use the profile information to upload assets to the deployment bucket

### Current Behavior

cdk-assets only uses the default profile. Output where default profile does not have access to the destination account, but the profile has
```
cdk-assets publish -p .\cdk.out\CdkassetTestStack.assets.json --profile=cdk-asset-test
info   : [0%] start: Publishing cce8267b26914adc2b23143d968a19d5d2f476abd83b954f6092d37ab2659431:<REDACTED>-eu-west-1
error  : [50%] fail: Bucket named 'cdk-hnb659fds-assets-<REDACTED>-eu-west-1' exists, but we dont have access to it.
info   : [50%] start: Publishing b34aec228a6313260b72fefaeedba363aba46ae6f45652338b3bf6c43e9b9be5:<REDACTED>-eu-west-1
error  : [100%] fail: Bucket named 'cdk-hnb659fds-assets-<REDACTED>-eu-west-1' exists, but we dont have access to it.
Failure: Error: Bucket named 'cdk-hnb659fds-assets-<REDACTED>-eu-west-1' exists, but we dont have access to it.
    at FileAssetHandler.publish (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\lib\private\handlers\files.js:65:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetPublishing.publishAsset (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\lib\publishing.js:133:17)
    at async AssetPublishing.publish (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\lib\publishing.js:48:23)
    at async publish (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\bin\publish.js:19:5)
    at async C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\bin\cdk-assets.js:39:9
    at async Object.handler (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\bin\cdk-assets.js:62:9)
Failure: Error: Bucket named 'cdk-hnb659fds-assets-<REDACTED>-eu-west-1' exists, but we dont have access to it.
    at FileAssetHandler.publish (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\lib\private\handlers\files.js:65:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetPublishing.publishAsset (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\lib\publishing.js:133:17)
    at async AssetPublishing.publish (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\lib\publishing.js:48:23)
    at async publish (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\bin\publish.js:19:5)
    at async C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\bin\cdk-assets.js:39:9
    at async Object.handler (C:\Users\PerGårdebrink\AppData\Roaming\npm\node_modules\cdk-assets\bin\cdk-assets.js:62:9)
```

### Reproduction Steps

* Setup a aws profile with permissions to the destination account
* Make sure the default profile does not have any permissions to the destination account
* Create a cdk test application (cdk init app --language) with a lambda or something that will use assets
* Define the stack to have a destination account defined
* cdk synth
* cdk-assets publish -p ./cdk.out/<Stack>.assets.json --profile=name-of-profile

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.1003.0 (build b242c23)

### Framework Version

_No response_

### Node.js Version

22.11.0

### OS

Windows

### Language

Python

### Language Version

3.11

### Other information

_No response_

### PR DESCRIPTION
**Pull request by iliapolo**
We neglected to configure the main credentials when assuming the file publishing role. The main credentials are where the profile is already configured. 

- Integration Test: https://github.com/aws/aws-cdk-cli-testing/pull/59

Fixes https://github.com/aws/aws-cdk-cli/issues/212

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license

### CODE REVIEW

File: packages/cdk-assets/lib/aws.ts [hunk 1]
```diff
@@ -228,6 +228,8 @@ export class DefaultAwsClient implements IAws {
       config.region = options.region;
       if (options.assumeRoleArn) {
         config.credentials = fromTemporaryCredentials({
+          // dont forget the credentials chain.
+          masterCredentials: config.credentials,
```
Comment (iliapolo) [inline packages/cdk-assets/lib/aws.ts:232]: Similar to what we have in the CDK CLI:

https://github.com/aws/aws-cdk-cli/blob/1bef26344b3e311fbac7241ffa9a3e05b195d6de/packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts#L357

> This is also why the CDK CLI wasn't affected.

Comment (iliapolo) [reply packages/cdk-assets/lib/aws.ts:232]: Hmm - this might be problematic if there are multiple assets to upload because it creates a self-assume. Checking.

Comment (iliapolo) [reply packages/cdk-assets/lib/aws.ts]: Yeap, this was wrong.

File: packages/cdk-assets/lib/aws.ts [hunk 2]
```diff
@@ -228,6 +235,8 @@ export class DefaultAwsClient implements IAws {
       config.region = options.region;
       if (options.assumeRoleArn) {
         config.credentials = fromTemporaryCredentials({
+          // dont forget the credentials chain.
+          masterCredentials: this.mainCredentials,
```
Comment (iliapolo) [inline packages/cdk-assets/lib/aws.ts:239]: We have something similar in CDK CLI:

https://github.com/aws/aws-cdk-cli/blob/1bef26344b3e311fbac7241ffa9a3e05b195d6de/packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts#L357

**Review by otaviomacedo — APPROVED** [review]
