### PR TITLE
fix(cli): write notices to stderr or don't write them at all

### LINKED ISSUE #33589: aws-cdk-notices: CDK Notice being parsed incorrectly causing YAMLSemanticError
### Describe the bug

When running a CDK Deploy, due to the CDK Notice, it seems to be picked up and parsed by YAML? 

This causes a YAMLSemanticError to be produced within one of aws-cdk yaml dependencies. 

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

2.177.0

### Expected Behavior

CDK Deploy should not fail on YAMLSemanticError.

### Current Behavior

Error Log Output after CDK Deploy:
```
/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/resolveSeq-d03cb037.js:1856
                doc.errors.push(new PlainValue.YAMLSemanticError(item, msg));
                                ^
YAMLSemanticError: Implicit map keys need to be followed by map values
    at resolveBlockMapItems (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/resolveSeq-d03cb037.js:1856:33)
    at Object.resolveMap [as resolve] (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/resolveSeq-d03cb037.js:1658:79)
    at resolveByTagName (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/resolveSeq-d03cb037.js:1430:25)
    at resolveTag (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/resolveSeq-d03cb037.js:1460:17)
    at resolveNodeValue (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/resolveSeq-d03cb037.js:1581:23)
    at Object.resolveNode (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/resolveSeq-d03cb037.js:1629:15)
    at parseContents (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/Document-9b4560a1.js:357:30)
    at Document.parse (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/Document-9b4560a1.js:615:5)
    at parseDocument (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/index.js:44:37)
    at Object.parse (/app/node_modules/aws-cdk-lib/node_modules/yaml/dist/index.js:55:15) {
  source: PlainValue {
    error: null,
    range: Range { start: 21443, end: 21531 },
    valueRange: Range { start: 21443, end: 21531 },
    props: [],
    type: 'PLAIN',
    value: null,
    resolved: Scalar {
      value: "\x1B[37mNOTICES         (What's this? https://github.com/aws/aws-cdk/wiki/CLI-Notices)\x1B[39m",
      range: [Array],
      type: 'PLAIN'
    }
  }
}
[06:22:00] failed command: npx ts-node ./src/index.ts
```

### Reproduction Steps

npx aws-cdk deploy

### Possible Solution

Stop CDK notices from being picked up by aws-cdk-lib yaml for parsing. 

### Additional Information/Context

Have tried using environment variable: `CDK_NOTICES=false` as suggested, but it doesn't ignore it. 

Ref: https://github.com/aws/aws-cdk/wiki/CLI-Notices#what-if-i-dont-want-notices

### CDK CLI Version

2.1000.3

### Framework Version

_No response_

### Node.js Version

22.14.0

### OS

Amazon Linux 2

### Language

TypeScript

### Language Version

TypeScript (5.3.3)

### Other information

Node 22.14.0 / NPM 10.9.2

### PR DESCRIPTION
**Pull request by rix0rrr**
(Replaces #188).

On CI systems, the CDK CLI tries to avoid writing to `stderr` because there are a couple of CI systems that are commonly configured to fail if any output is written to `stderr`. That means all output, like notices, must go to `stdout`.

Some commands (like `cdk synth` or `cdk bootstrap --show-template`) produce usable output on `stdout`, and these are commonly scripted, like piping their output to a file.

However, because notices must go to `stdout`, these now interfere with the output of these commands.

This needs a more thorough reworking of the CLI output streams, but there is a risk of affecting users who are currently relying on the fact that all output goes to `stdout`.

In this PR, we are doing the first steps to solving this situation:

- Notices will always go to `stderr`, so that they will never interfere with `stdout` anymore.
- We try to detect what CI system we are running on, and we will completely suppress notices *unless* we determine that we are running on a CI system where it is "safe" to write to `sterr` (fail closed).

"Safe" in this case means that the CI system doesn't come with an easy to toggle checkbox that makes commands fail based on what they print, instead of their exit codes. The only systems I'm aware of that have this checkbox are "Azure DevOps", and "TeamCity running PowerShell scripts".

Even though we know the systems that are "unsafe", we will only show notices on systems known to be "safe".

Fixes https://github.com/aws/aws-cdk/issues/33589.

Also in this PR, because this grew.

* Introduce `IoDefaultMessages` in the CLI package, which helps migrate "legacy" logging code to just emit default warning/info/etc messages to the IoHost.
* Removed the ability to log with a `{ message: 'asdf' }` object to the global logger functions. This wasn't being used anywhere other than tests, and it's sort of pointless: if you know the code you should be using the `MessageMaker` to make a message object; if you don't know the code you can emit a string. There is no need to look up the right code given a level and a message object.
* Make it possible for result types to be any type, not just object types. This is necessary to cover the "result" from legacy logging, where the result is just a string.
* Updated many tests in a test file (`cli-io-host.test.ts`) that failed type checking, but succeeded running, and therefore didn't fail the build of #220.
* Centralized `TestIoHost` into the helper package, and renamed it to `MockIoHost`.
* Introducing a `FakeIoHost` in the CLI package to assert on messages emitted to an `IoHost`. 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license

### CODE REVIEW

File: packages/aws-cdk/lib/logging.ts [hunk 1]
```diff
@@ -185,3 +170,60 @@ export const success = (input: LogInput<'I'>, ...args: unknown[]) => {
...
 };
+
+/**
+ * Helper class to emit standard log messages to an IoHost
+ *
+ * It wraps an `IoHelper`, and adds convenience methods for the various log
+ * levels, same as the global ones but scoped to a particular `IoHost` instead
+ * of the global singleton one.
+ */
+export class IoLogger {
```
Comment (mrgrain) [inline packages/aws-cdk/lib/logging.ts:181]: So now we have two sets of deprecated logging functions?

Comment (mrgrain) [reply packages/aws-cdk/lib/logging.ts:181]: I don't like anything that's permanent to be called logging. It gives a false impression to what it's doing. So maybe this?

```suggestion
export class IoMessageEmitter {
```

File: packages/aws-cdk/lib/notices.ts [hunk 2]
```diff
@@ -298,10 +301,10 @@ export class Notices {
 
   private readonly context: Context;
   private readonly output: string;
-  private readonly shouldDisplay: boolean;
   private readonly acknowledgedIssueNumbers: Set<Number>;
   private readonly includeAcknowlegded: boolean;
   private readonly httpOptions: SdkHttpOptions;
+  private readonly ioHostEmitter: IoLogger;
```
Comment (mrgrain) [inline packages/aws-cdk/lib/notices.ts:307]: Could we use the IoHelper here?

File: packages/aws-cdk/test/util/fake-io-host.ts
[the remark this answers is not in the document]
Comment (mrgrain) [reply packages/aws-cdk/test/util/fake-io-host.ts:1]: This is on me for starting a new directory without moving the old code.

FWIW I try to avoid `util` in the test directory because there also is a module called `util` and it just confuses people as to whether this directory is used for test utilities or for tests testing the `util` module.

File: packages/@aws-cdk/toolkit-lib/docs/message-registry.md [hunk 3]
```diff
@@ -51,6 +51,10 @@ group: Documents
 | `CDK_TOOLKIT_I9100` | Bootstrap progress | `info` | {@link BootstrapEnvironmentProgress} |
 | `CDK_TOOLKIT_I9900` | Bootstrap results on success | `result` | [cxapi.Environment](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_cx-api.Environment.html) |
 | `CDK_TOOLKIT_E9900` | Bootstrap failed | `error` | {@link ErrorPayload} |
+| `CDK_TOOLKIT_I0100` | Notices decoration (the header or footer of a list of notices) | `info` | n/a |
+| `CDK_TOOLKIT_W0101` | A notice that is marked as a warning | `warn` | n/a |
+| `CDK_TOOLKIT_E0101` | A notice that is marked as an error | `error` | n/a |
+| `CDK_TOOLKIT_I0101` | A notice that is marked as informational | `info` | n/a |
```
Comment (mrgrain) [inline packages/@aws-cdk/toolkit-lib/docs/message-registry.md:57]: This is probably out-of-scope for this PR, but I wonder if we could give these messages a useful payload like the raw notices object.

File: packages/aws-cdk/lib/logging.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/aws-cdk/lib/logging.ts:181]: Ha, 100% what I had first and then I changed it :D

**Review by mrgrain — APPROVED** [review]

**Comment by mrgrain** [comment]
@rix0rrr FYI this has a genuine integ test failure

https://github.com/aws/aws-cdk-cli/actions/runs/13791337672/job/38573116246?pr=221#step:13:667

**Comment by rix0rrr** [comment]
> FYI this has a genuine integ test failure

Good point, and it can't be helped, really. 

https://github.com/aws/aws-cdk-cli-testing/pull/57
