### PR TITLE
fix(cloud-assembly-api): propagate load options to nested assemblies

### LINKED ISSUE #749: (toolkit-lib): cannot disable cloud assembly version check on nested assemblies
### Describe the bug

Using `toolkit.fromAssemblyDirectory` it should be possible to skip the assembly version check with `loadAssemblyOptions.checkVersion = false` (see #201), but it does not work if there are _any_ nested assemblies (e.g. Stages).

```ts
  const toolkit = new Toolkit({
    ioHost: new NonInteractiveIoHost({
      logLevel: 'trace',
    }),
  });
  const assembly = await toolkit.fromAssemblyDirectory(
    path.join(__dirname, '../../cdk.out'),
    {
      failOnMissingContext: false,
      loadAssemblyOptions: {
        checkVersion: false,
      },
    },
  );

```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Last Known Working CDK Version

_No response_

### Expected Behavior

Setting `checkVersion: false` should completely disable the version check.

### Current Behavior

If there are any nested assemblies, it will fail with the below error.

```console
Error: Cloud assembly schema version mismatch: Maximum schema version supported is 44.x.x, but found 45.0.0. You need at least CLI version 2.1020.2 to read this manifest.
    at Function.validate (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.ts:204:13)
    at Function.loadManifest (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.ts:264:14)
    at Function.loadAssemblyManifest (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.ts:95:21)
    at new CloudAssembly (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.ts:68:39)
    at NestedCloudAssemblyArtifact.get (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/cx-api/lib/artifacts/nested-cloud-assembly-artifact-aug.ts:14:24)
    at <anonymous> (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.ts:156:69)
    at Array.map (<anonymous>)
    at search (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.ts:156:54)
    at CloudAssembly.get stacksRecursively (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.ts:160:12)
    at StackAssembly.selectStacksV2 (/Users/chall/personal/cdk-version-check-repro/scripts/example/node_modules/@aws-cdk/toolkit-lib/lib/api/cloud-assembly/private/stack-assembly.ts:43:66)
```

### Reproduction Steps

I've created a repro here https://github.com/corymhall/cdk-version-check-repro

### Possible Solution

It looks like this is caused by the loading behavior of nested assemblies. The load options are not being passed through. Would it make sense to disable the checks by default on nested assemblies? Wouldn't the check on the top level cover all nested assemblies?

https://github.com/aws/aws-cdk/blob/a2c633f1e698249496f11338312ab42bd7b1e4f0/packages/aws-cdk-lib/cx-api/lib/artifacts/nested-cloud-assembly-artifact-aug.ts#L11-L18

### Additional Information/Context

_No response_

### CDK CLI Version

2.1022.0

### Framework Version

_No response_

### Node.js Version

22.14.0

### OS

MacOS

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by juho9000**
Fixes #749

Nested assemblies (e.g. Stages) are instantiated without the parent's `LoadManifestOptions`, so setting `skipVersionCheck: true` on the root assembly has no effect on nested assemblies — they still fail with a version mismatch error.

Store `loadOptions` on `CloudAssembly` and pass them through when creating nested assemblies via `NestedCloudAssemblyArtifact.nestedAssembly`.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license

### CODE REVIEW

File: packages/@aws-cdk/cloud-assembly-api/lib/cloud-assembly.ts [hunk 1]
```diff
@@ -102,12 +102,18 @@ export class CloudAssembly implements ICloudAssembly {
    */
   public readonly manifest: cxschema.AssemblyManifest;
 
+  /**
+   * The load options used to create this assembly, propagated to nested assemblies.
+   */
+  public readonly loadOptions?: cxschema.LoadManifestOptions;
```
Comment (rix0rrr) [inline packages/@aws-cdk/cloud-assembly-api/lib/cloud-assembly.ts]:
```suggestion
  private readonly loadOptions?: cxschema.LoadManifestOptions;
```

**Review by rix0rrr — APPROVED** [review]
